name: ci

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Git clone
        id: git_clone
        run: git clone -b "develop" --depth 1 https://github.com/qyvlik/Auto-GPT.git

      -
        name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: ./Auto-GPT
          push: true
          tags: qyvlik/autogpt:develop
